image: python:3.7
test:
  script:
    - pip install mock
    - pip install click
    - pip install requests
    - pip install coverage
    - coverage run WeatherForecast.spec.py
    - coverage report
